services:
  s3parq:
    image: s3parq
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1 # s3 is always in us-east-1
      - S3_BUCKET=${S3_BUCKET}
    command: ["pytest", "tests", "-k", "test_integration"]
